# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SavePhotos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'SwiftyKeychainKit', '1.0.0-beta.2'
  
   pod 'Firebase/Crashlytics'

end
